version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/app # Mounts your local code to the container
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: [ 'flask', 'run', '--host=0.0.0.0', '--port=5000' ]
